

spring.application.name: demo
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/ec_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username: root
spring.datasource.password: password
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
